// Generated by CoffeeScript 1.8.0
(function() {
  define(function(require) {
    var config;
    return config = {
      DatabasePath: '',
      DatabaseBackend: 'PouchDB',
      ReadOnly: false,
      timeout: 3000
    };
  });

}).call(this);

//# sourceMappingURL=config.js.map
