// Generated by CoffeeScript 1.8.0
(function() {
  define(function(require) {
    var Inquisitor, defaultConfig;
    defaultConfig = require('./config');
    return Inquisitor = (function() {
      function Inquisitor(config) {
        console.log('inquisitor');
        this.config = config;
        if (config != null) {
          this.config = defaultConfig;
        }
      }

      Inquisitor.prototype.config = null;

      Inquisitor.prototype.open = function(database) {};

      return Inquisitor;

    })();
  });

}).call(this);

//# sourceMappingURL=Inquisitor.js.map
