// Generated by CoffeeScript 1.8.0
(function() {
  define(function(require) {
    var Iterator;
    return Iterator = (function() {
      function Iterator() {}

      Iterator.prototype.Tagger = function() {};

      Iterator.prototype.TagResults = function() {};

      Iterator.prototype.Result = function() {};

      Iterator.prototype.ResultTree = function() {};

      Iterator.prototype.NextPath = function() {};

      Iterator.prototype.Contains = function() {};

      Iterator.prototype.Reset = function() {};

      Iterator.prototype.Clone = function() {};

      Iterator.prototype.Stats = function() {};

      Iterator.prototype.Size = function() {};

      Iterator.prototype.Type = function() {};

      Iterator.prototype.Optimize = function() {};

      Iterator.prototype.SubIterators = function() {};

      Iterator.prototype.Describe = function() {};

      Iterator.prototype.Close = function() {};

      Iterator.prototype.UID = function() {};

      Iterator.prototype.Next = function() {};

      Iterator.prototype.Height = function() {};

      return Iterator;

    })();
  });

}).call(this);

//# sourceMappingURL=Iterator.js.map
