// Generated by CoffeeScript 1.8.0
(function() {
  define(function(require) {
    var Tagger;
    return Tagger = (function() {
      function Tagger() {
        ({
          tags: null,
          fixedTags: null
        });
      }

      Tagger.prototype.Add = function(tag, value) {
        return tags;
      };

      return Tagger;

    })();
  });

}).call(this);

//# sourceMappingURL=Tagger.js.map
