// Generated by CoffeeScript 1.8.0
(function() {
  define(function(require) {
    var Types;
    return Types = (function() {
      function Types() {}

      Types.prototype.InvalidType = "invalid";

      Types.prototype.All = "all";

      Types.prototype.And = "and";

      Types.prototype.Or = "or";

      Types.prototype.HasA = "hasa";

      Types.prototype.LinksTo = "linksto";

      Types.prototype.Comparison = "comparison";

      Types.prototype.Null = "null";

      Types.prototype.Fixed = "fixed";

      Types.prototype.Not = "not";

      Types.prototype.Optional = "optional";

      Types.prototype.Materialize = "materialize";

      return Types;

    })();
  });

}).call(this);

//# sourceMappingURL=Types.js.map
